{% set name = "apache-airflow-providers-atlassian-jira" %}
{% set version = "3.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_atlassian_jira-{{ version }}.tar.gz
  sha256: 42d4a0b6336d1ac22d8ca802cd3a04ac2f1b8779177619b1e8fc9bb7563076c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-compat >=1.6.1
    - atlassian-python-api >3.41.10

test:
  imports:
    - airflow.providers.atlassian.jira
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-atlassian-jira for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/atlassian/jira/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-atlassian-jira/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
