{% set name = "apache-airflow-providers-atlassian-jira" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_atlassian_jira-{{ version }}.tar.gz
  sha256: 21592f6545ad0337503c1a5faf6cd9c4612992d5afd860079a5270d4b7397195

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - beautifulsoup4
    - python >=3.8
    - apache-airflow >=2.6.0
    - atlassian-python-api >=1.14.2,!=3.41.6

test:
  imports:
    - airflow.providers.atlassian.jira
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-atlassian-jira for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/atlassian/jira/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-atlassian-jira/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
